cleanup code & documentation

diff --git a/bin/simplevisor-control b/bin/simplevisor-control
--- a/bin/simplevisor-control
+++ b/bin/simplevisor-control
@@ -4,47 +4,47 @@
 # 
 # Control script for simplevisor: simple daemons supervisor
 #
-#
 
 RETVAL=0
 
 [ -r "/etc/sysconfig/simplevisor" ] && . "/etc/sysconfig/simplevisor"
 
-EXECUTABLE=`which simplevisor`
-test -x ${EXECUTABLE} || exit 5
-COMMAND_PREFIX="/usr/bin/python ${EXECUTABLE}"
-
-NAME=${SIMPLEVISOR_NAME-simplevisor}
-USER=${SIMPLEVISOR_USER}
+CMD=${SIMPLEVISOR_CMD-`which simplevisor 2>/dev/null`}
+if [ -z "${CMD}" -o ! -x "${CMD}" ]; then
+    echo "simplevisor not found"
+    exit 5
+fi
 
 CONF=${SIMPLEVISOR_CONF-/etc/${NAME}/${NAME}.conf}
-if [ ! -r ${CONF} ] ; then
+if [ ! -r "${CONF}" ]; then
     echo "configuration file not readable"
     exit 5
 fi
 
+USER=${SIMPLEVISOR_USER}
+NAME=${SIMPLEVISOR_NAME-simplevisor}
 PIDFILE=${SIMPLEVISOR_PIDFILE-/var/run/${NAME}.pid}
 LOCKFILE=${SIMPLEVISOR_LOCKFILE-/var/lock/subsys/${NAME}}
-MAX_AGE=${SIMPLEVISOR_MAX_AGE-10}
+MAXAGE=${SIMPLEVISOR_MAXAGE-10}
 
-if [ -z "$SIMPLEVISOR_USER" -o `id -un` = "$SIMPLEVISOR_USER" ] ; then
-    COMMAND="${COMMAND_PREFIX} -p ${PIDFILE} --conf ${CONF}"
+if [ -z "${USER}" -o `id -un` = "${USER}" ]; then
+    COMMAND="${CMD} --pidfile ${PIDFILE} --conf ${CONF}"
 else
-    COMMAND="sudo -n -u ${SIMPLEVISOR_USER} ${COMMAND_PREFIX} -p ${PIDFILE} --conf ${CONF}"
+    COMMAND="sudo -n -u ${USER} ${CMD} --pidfile ${PIDFILE} --conf ${CONF}"
 fi
 
 SUBPATH="$2"
 
 start() {
     echo -n "Starting ${NAME}: "
-    if [ "x${SUBPATH}" = "x" ] ; then
+    if [ "x${SUBPATH}" = "x" ]; then
         ${COMMAND} --daemon start
     else
         ${COMMAND} start ${SUBPATH}
     fi
     RETVAL=$?
     [ "x${SUBPATH}" != "x" ] && return
-    if [ $RETVAL = 0 ] ; then
+    if [ ${RETVAL} -eq 0 ]; then
         touch ${LOCKFILE}
         echo "started"
     else
@@ -57,8 +57,8 @@ status(){
     ${COMMAND} status ${SUBPATH}
     RETVAL=$?
     [ "x${SUBPATH}" != "x" ] && return
-    if [ $RETVAL = 0 ] ; then
-        ok=`find ${PIDFILE} -mmin -${MAX_AGE}`
+    if [ ${RETVAL} -eq 0 ]; then
+        ok=`find ${PIDFILE} -mmin -${MAXAGE}`
         if [ "x$ok" = "x" ]; then
             date=`date +"%Y/%m/%d-%H:%M:%S" -r ${PIDFILE}`
             echo "stuck since $date"
@@ -74,7 +74,7 @@ stop() {
     ${COMMAND} stop ${SUBPATH}
     RETVAL=$?
     [ "x${SUBPATH}" != "x" ] && return
-    if [ $RETVAL = 0 ] ; then
+    if [ ${RETVAL} -eq 0 ]; then
         rm -f ${LOCKFILE} ${PIDFILE}
         echo "stopped"
     else
@@ -86,7 +86,7 @@ stop_supervisor() {
     echo -n "Stopping supervisor ${NAME}: "
     ${COMMAND} stop_supervisor
     RETVAL=$?
-    if [ $RETVAL = 0 ] ; then
+    if [ ${RETVAL} -eq 0 ]; then
         rm -f ${LOCKFILE} ${PIDFILE}
         echo "supervisor stopped"
     else
@@ -113,7 +113,7 @@ case "$1" in
   restart)
     echo "Restarting ${NAME}"
     stop
-    if [ ${RETVAL} = 1 ] ; then
+    if [ ${RETVAL} -eq 1 ]; then
         echo "skipping start action"
     else
         sleep 0.3
@@ -123,7 +123,7 @@ case "$1" in
   restart-supervisor)
     echo "Restarting supervisor ${NAME}"
     stop_supervisor
-    if [ ${RETVAL} = 1 ] ; then
+    if [ ${RETVAL} -eq 1 ]; then
         echo "skipping start action"
     else
         sleep 0.3
@@ -142,7 +142,7 @@ case "$1" in
     ;;
 esac
 
-exit $RETVAL
+exit ${RETVAL}
 
 =head1 NAME
 
@@ -150,16 +150,14 @@ simplevisor-control - run simplevisor as a service
 
 =head1 SYNOPSIS
 
-B<simplevisor-control>
-command [path]
+B<simplevisor-control> command [path]
 
 =head1 DESCRIPTION
 
-simplevisor-control command can be used to run simplevisor as a service.
+B<simplevisor-control> command can be used to run simplevisor as a service.
 
 If this script is used the pidfile value specified in the simplevisor
 configuration file will be ignored.
-
 
 =head1 OPTIONS
 
@@ -172,16 +170,16 @@ look at simplevisor man page for path behavior.
 
 =head1 EXAMPLES
 
-On Linux you can look at the script shipped in the examples folder
-which is called simplevisor-new-instance, it creates folders and
-the configuration to run a simplevisor instance.
+On Linux you can look at the script shipped in the examples folder which is
+called simplevisor-new-instance, it creates folders and the configuration to
+run a simplevisor instance.
 
     mkdir -p /var/lib/myinstance/bin
     mkdir -p /var/lib/myinstance/data
     mkdir -p /var/lib/myinstance/etc
 
-Create a file /var/lib/myinstance/bin/service with content
-and make it executable:
+Create a file /var/lib/myinstance/bin/service with content and make it
+executable:
 
     #!/bin/sh
     #
